In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import random


Task 1

In [ ]:
# np.random.seed(42)
tot=500*365
t1=np.random.uniform(-10,40,(500,365))
t2=np.random.uniform(0,100,(500,365))
num_nan_t1 = int(0.05 * len(t1))
nan_indices_t1 = np.random.choice(len(t1), num_nan_t1, replace=False)
t1[nan_indices_t1] = np.nan
num_nan_t2 = int(0.05 * len(t2))
nan_indices_t2 = np.random.choice(len(t2), num_nan_t2, replace=False)
t2[nan_indices_t2] = np.nan
a1 = np.sum(np.isnan(t1))
a2 = np.sum(np.isnan(t2))


Task 2

In [ ]:
print("Number of missing (NaN) values in t1:", a1)
print("Number of missing (NaN) values in t2:", a2)


Task 3

In [ ]:
temp_in_faren=(t1*1.8)+32
feel_like = temp_in_faren + 0.55 * (t2 - 50)
feel_like=np.where(feel_like>80,80,feel_like)


Task 4

In [ ]:
for i in range(365):
    a=np.nanmean(temp_in_faren[i][0:32])
    print(f"Average temperature of January of location {i+1}:\t",a)


Task 5

In [ ]:
gen=np.where(t1>35,np.nan,t1)
null_values_per_location = np.isnan(gen).sum(axis=0)
cnt=1
for i in null_values_per_location:
	print(f"Null values of location {i} after marking extreme temperatures:\t{i}")
	cnt+=1


Task 6

In [ ]:
t1=np.random.uniform(-10,40,(500,365))
a=t1[:,:364]
a=list(a.reshape(500,91,4))
for i in range(len(a)):
    print(f"Quarterly sum of temp of 1st season in location {i+1}:\t",sum(a[i][0][:]))
    print(f"Quarterly sum of temp of 2nd season  in location {i+1}:\t",sum(a[i][1][:]))
    print(f"Quarterly sum of temp of 3rd season  in location {i+1}:\t",sum(a[i][2][:]))
    print(f"Quarterly sum of temp of 4th season  in location {i+1}:\t",sum(a[i][3][:]))
    print()


Task 7

In [ ]:
t2 = np.random.uniform(0, 100, (500, 365))
a = np.where(t2 < 30, "Dry", np.where(t2 > 70, "Humid", "Normal"))
dry_days_per_location = np.sum(a == "Dry", axis=1)
humid_days_per_location = np.sum(a == "Humid", axis=1)
for i in range(500):
    print(f"Location {i+1}: Dry days = {dry_days_per_location[i]}, Humid days = {humid_days_per_location[i]}")


Task 8

In [ ]:
pressure_variation = np.linspace(-5, 5, 500)  
adjusted_temperature_data = t1 + pressure_variation[:, np.newaxis]
print(f"Adjusted temperature data (sample):\n{adjusted_temperature_data[:5, :5]}")


Adjusted temperature data (sample):
[[ -7.18880846  17.7293017   18.82336654   1.83586099 -12.97132636]
 [ -7.00009366  23.66397494   2.08196497  -5.96978534  29.91901157]
 [ 32.35157724  13.71075052  29.70966664  19.39920607   0.0872575 ]
 [  3.06658153  -3.05683499  17.13733108 -14.47533211  17.32855932]
 [ 15.07204386  -4.20533453  23.35414016   7.46853506   8.65153936]]
